### PR TITLE
Added an optional website value to Plugin Description

### PR DESCRIPTION
**Pull request by TheDiamondYT1**

### CODE REVIEW

**Comment by minecrafter** [comment]
Not sure how beneficial this will be. Any justification?

**Comment by TheDiamondYT1** [comment]
if you add functionality for the /version command to display plugin info like Bukkit, you can print the website defined here like Bukkit.

It could also be used inside the plugin. Ive seen Bukkit, Nukkit, and PocketMine plugins that display the plugin name, version, and sometimes website by using getPlugin().getDescription().getFullName() etc

**Comment by minecrafter** [comment]
Fair enough, have you tested this?

**Comment by TheDiamondYT1** [comment]
For example Factions /f version uses PluginDescription getFullName(). Obviously it doesnt include website in getFullName() but some plugins use it

**Comment by TheDiamondYT1** [comment]
Ummm it compiled and runs but i havent tried using it in a plugins

**Comment by TheDiamondYT1** [comment]
I didnt have time i had to come off pc

**Comment by minecrafter** [comment]
Might merge tomorrow

**Comment by TheDiamondYT1** [comment]
Alright

**Comment by minecrafter** [comment]
Not currently a priority. Not merging for now.

**Comment by TheDiamondYT1** [comment]
fair enough.

**Pull request closed without merging**
