### PR TITLE
Added PlayerJoinEvent

### PR DESCRIPTION
**Pull request by TheDiamondYT1**
Obviously the join message wont do anything untill you make it broadcast the join to the server, but you can use it for other things for now.

### CODE REVIEW

**Comment by TheDiamondYT1** [comment]
I havent tested it. Why? Run the server and join the game. Theres so much debug spam its unreal.

**Comment by TheDiamondYT1** [comment]
Okay it works i disabled debug by editing log4j.xml

**Comment by minecrafter** [comment]
This is fired too early. `PlayerJoinEvent` should really only be fired when the player has been fully spawned into the world.

**Comment by TheDiamondYT1** [comment]
Hmmm. I checked through Nukkit and its fired after the adventure settings have been sent. It does work however in this PR. I made it send a message to the player on join and it works. I only added so i could start on some plugins

**Comment by TheDiamondYT1** [comment]
I can update the PR to fix it

**Comment by minecrafter** [comment]
Voxelwind does not intend to be a copy of Nukkit and/or PocketMine. That's something I am against.

**Comment by TheDiamondYT1** [comment]
I know i dont want it to be. But an event fired when a player joins is just basic stuff that it should have. Ive fixed it in latest commit.

**Comment by minecrafter** [comment]
Alright - please squash your commits.

**Comment by TheDiamondYT1** [comment]
Cant you squash it on merge? Im sure i saw an option

**Comment by TheDiamondYT1** [comment]
Sorry, closing this. I failed at rebasing. It will create a new commit with chat even as well to make up for the spam (And i need chat event then i will stop making PRs)

**Pull request closed without merging**
